#ifdef PROBLEM_DESCRIPTION

Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
Triangle 	  	P3,n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Square 	  		P4,n=n2 	  		1, 4, 9, 16, 25, ...
Pentagonal 	  	P5,n=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	P6,n=n(2n−1) 	  	1, 6, 15, 28, 45, ...
Heptagonal 	  	P7,n=n(5n−3)/2 	  	1, 7, 18, 34, 55, ...
Octagonal 	  	P8,n=n(3n−2) 	  	1, 8, 21, 40, 65, ...

The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

    The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
    Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
    This is the only set of 4-digit numbers with this property.

Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.

#endif

using namespace std;

#include <vector>
#include <stdio.h>
#include <math.h>

vector<long> g;

long isSquare(long n)
{
	long sa = sqrt((double) n);
	if (sa * sa == n) return sa;
	return 0;
}

long getSquare(long n)
{
	return n * n;
}

long isTriangle(long p)
{
	long t = isSquare(1 + 8 * p);
	if (t) return (t - 1) / 2;
	return 0;
}

long getTriangle(long n)
{
	return n * (n + 1) / 2;
}

long isPentagonal(long p)
{
	long t = isSquare(1 + 24 * p);
	if (!t) return 0;
	t += 1; // is t divisible by six??
	if (t % 6 == 0) return t / 6;
	return 0;
}

long getPentagonal(long n)
{
	return n * (3 * n - 1) / 2;
}

long isHexagonal(long p)
{
	long t = isSquare(1 + 8 * p);
	if (!t) return 0;
	t += 1; // is t divisible by four??
	if (t % 4 == 0) return t / 4;
	return 0;
}

long getHexagonal(long n)
{
	return n * ( 2 * n - 1 );
}

long isHeptagonal(long p)
{
	long t = isSquare(9 + 40 * p);
	if (!t) return 0;
	t += 3; // is t divisible by 10 ??
	if (t % 10 == 0) return t / 10;
	return 0;
}

long getHeptagonal(long n)
{
	return n * (5 * n - 3 ) / 2;
}

long isOctagonal(long p)
{
	long t = isSquare(4 + 12  * p);
	if (!t) return 0;
	t += 2; // is t divisible by 6 ??
	if (t % 6 == 0) return t / 6;
	return 0;
}

long getOctagonal(long n)
{
	return n * ( 3 * n - 2 );
}


#define TRI(p)	isTriangle(p) ? 'Y' : 'N'
#define SQU(p)	isSquare(p) ? 'Y' : 'N'
#define PEN(p)	isPentagonal(p) ? 'Y' : 'N'
#define HEX(p)	isHexagonal(p) ? 'Y' : 'N'
#define HEP(p)	isHeptagonal(p) ? 'Y' : 'N'
#define OCT(p)	isOctagonal(p) ? 'Y' : 'N'

#define MAXN 100
long tri4[MAXN];
int  tric = 0;
long squ4[MAXN];
int  squc = 0;
long pen4[MAXN];
int  penc = 0;
long hex4[MAXN];
int  hexc = 0;
long hep4[MAXN];
int  hepc = 0;
long oct4[MAXN];
int  octc = 0;

bool secondZero(long n)
{
	n /= 10;
	if (n % 10 == 0) return true;
	return false;
}

void	fill(long a[MAXN], int &n, long (*f)(long), const char *s)
{
	n = 0;
	long k = 1;
	while(f(k) < 1000) k++;
	long fk = f(k);
	while(fk < 10000)
	{
		if (!secondZero(fk))	// do not include numbers with 0 as 10's digit
			a[n++] = fk;
		fk = f(++k);
	}
	a[n] = -1;
	
	printf("\n%s Numbers:\n", s);
	for (int j = 0; j < n; j++)
	{
		//printf("%4ld  ::  %4ld\n", sk++, a[j]);
		printf("%4ld ", a[j]);
		if ( (j+1) % 10 == 0)printf("\n");
	}
}

#define LOW(x)	(x)%100
#define HIGH(x)	(x)/100

bool	low_check(long v, long *a)
{
	while (*a > 0)
	{
		if (v == LOW(*a)) return true;
		a++;
	}
	return false;
}

bool	high_check(long v, long *a)
{
	while (*a > 0)
	{
		if (v == HIGH(*a)) return true;
		a++;
	}
	return false;
}
void remdigs(long *a, long *b, long *c, long *d, long *e, long *f)
{
	// eliminate a[n] if LOW[a[n]] does NOT appear in any of the b, c, d, e, f HIGH
	//      AND       if HIGH(a[n]) does NOT appear in any of the b, c, d, e, f, LOW
	bool low_found = false;
	bool high_found = false;
	while (*a > 0)
	{
		low_found = low_check(HIGH(*a), b) || low_check(HIGH(*a), c) ||
					low_check(HIGH(*a), d) || low_check(HIGH(*a), e) || 
					low_check(HIGH(*a), f);
		high_found = high_check(LOW(*a), b) || high_check(LOW(*a), c) ||
					 high_check(LOW(*a), d) || high_check(LOW(*a), e) ||
					 high_check(LOW(*a), f);
		if (!low_found || !high_found) { 
			printf("%ld eliminated\n", *a); 
			*a = 0; 
		}
		a++;
	}
}

void out(const char *s, long *a) // added compression
{
	printf("%s\n", s);
	int   perline = 0;
	long  *comp = a;
	while (*a >= 0)
	{
		if (*a != 0)
		{
			perline++;
		    printf("%4ld  ", *a);
		    if (perline > 9) {
				perline = 0;
				printf("\n");
			}
			*comp = *a;
			comp++;
		}
		a++;
	}
	*comp = -1;
	printf("\n");
}

typedef enum{Triangle, Square, Pentagon, Hexagon, Heptagon, Octagon} geonum_t;
				
// geonum is a geomtric number
typedef struct {
	geonum_t	ct;
	long  num;
	long  low;
	long  high;
} geonum;

vector<geonum> glist;

class path{
	public:
		path();
		bool add(geonum_t ct, long num);	// returns true if added, 
		bool add(geonum c);	// returns true if added, 
		void reset();
		bool complete();	// returns true if path is complete 6 elements, 1 of each
		size_t size() { return v.size(); };
		void out() { for (size_t i = 0; i < v.size(); i++)
					 {
						 printf("%d - num: %ld   low: %ld   high: %ld\n",
							v[i].ct, v[i].num, v[i].low, v[i].high);
					 }};
	private:
		bool have[6];
		int  high_match;
		vector<geonum> v;
};

void	path::reset()
{
	for (int i = 0; i < 6; i++) have[i] = false;
	high_match = 0;
	v.clear();
}

path::path()
{
	reset();
}

bool
path::add(geonum_t ct, long num)
{
	geonum a;
	a.ct = ct;
	a.num = num;
	a.low = LOW(num);
	a.high = HIGH(num);
	//printf("Adding num: %ld  type: %d\n", a.num, a.ct);
	return add(a);
}

bool
path::add(geonum c)
{
	if (have[c.ct]) return false;
	//printf("++1++Adding num: %ld  type: %d\n", c.num, c.ct);
	if ((v.size() == 5) && (high_match != c.num)) return false;
	//printf("++2++Adding num: %ld  type: %d\n", c.num, c.ct);
	if ((v.size() > 0) && (v.size() < 5) && (high_match != HIGH(c.num)))
		return false;
	//printf("++3++Adding num: %ld  type: %d\n", c.num, c.ct);
	// if we get here, ct/num should be added
	
	have[c.ct] = true;
	v.push_back(c);
	if (v.size() == 5) high_match = c.num;
	else high_match = LOW(c.num);
	return true;
}

bool
path::complete() { return v.size() == 6; }

static int hep4Index = 0;

bool createPath(path p)
{
	printf("createPath: p.size(): %lu\n", p.size());
	if (p.size() == 0)
	{
		// start with heptagon ALWAYS
	printf("createPath: index: %d adding %ld type: %d\n",hep4Index, hep4[hep4Index], Heptagon);
		p.add(Heptagon, hep4[hep4Index++]);
	printf("----createPath: p.size(): %lu\n", p.size());
		return createPath(p);
	}
	else if (p.size() <= 5)
	{
		p.out();
		for (size_t i = 0; i < glist.size(); i++)
		{
			if (p.add(glist[i])) createPath(p);
		}
		return false;
	}
		
		
	if (p.size() == 6) // we're at the end, need to match high and low
	{
		p.out();
		return true;
	}
	return false;
}

void addthem(long *g, geonum_t gt)
{
	while (*g >= 0)
	{
		if (*g != 0)
		{
			geonum gn;
			gn.ct = gt;
			gn.num = *g;
			gn.low = LOW(*g);
			gn.high = HIGH(*g);
			glist.push_back(gn);
		}
		g++;
	}
}

void whatsleft()
{
	out("Triangle numbers:", tri4);
	addthem(tri4, Triangle);
	out("Square numbers:", squ4);
	addthem(squ4, Square);
	out("Pentagon numbers:", pen4);
	addthem(pen4, Pentagon);
	out("Hexagon numbers:", hex4);
	addthem(hex4, Hexagon);
	out("Heptagon numbers:", hep4);
	//addthem(hep4, Heptagon);
	out("Octagon numbers:", tri4);
	addthem(tri4, Octagon);
}


int main()
{
	//printf("  P    Tri   Squ   Pen   Hex   Hep   Oct\n");
	//for (long p = 1; p <= 65; p++)
	//{
	//	printf("%3ld %5c %5c %5c %5c %5c %5c\n",
	//	   p, TRI(p), SQU(p), PEN(p), HEX(p), HEP(p), OCT(p));
	//}
	// n = 19 -> first 4-digit octagonal number:: 1045
	// n = 58 -> last 4 digit octagonal number:: 9976
	//for (long n = 19; n <= 58; n++)
	//{
	//	long oct = n * (3 * n - 2);
	//	long f2 = oct % 100;
	//	long l2 = oct / 100;
	//	if (isTriangle(oct) && isSquare(oct) && isPentagonal(oct) &&
	//		isHexagonal(oct) && isHeptagonal(oct))
	//	{
	fill(tri4, tric, getTriangle, "Triangle");
	fill(squ4, squc, getSquare, "Square");
	fill(pen4, penc, getPentagonal, "Pentagon");
	fill(hex4, hexc, getHexagonal, "Hexagon");
	fill(hep4, hepc, getHeptagonal, "Heptagon");
	fill(oct4, octc, getOctagonal, "Octagon");
	for (int i = 0; i < 1; i++)
	{
		remdigs(tri4, squ4, pen4, hex4, hep4, oct4);
		remdigs(squ4, tri4, pen4, hex4, hep4, oct4);
		remdigs(pen4, tri4, squ4, hex4, hep4, oct4);
		remdigs(hex4, tri4, squ4, pen4, hep4, oct4);
		remdigs(hep4, tri4, squ4, pen4, hex4, oct4);
		remdigs(oct4, tri4, squ4, pen4, hex4, hep4);

		whatsleft();
	}
	path p;
	for (int i = 0; hep4[i] >= 0; i++)
		printf("i: %d   hep: %ld\n", i, hep4[i]);
	printf("main: index: %d adding %ld type: %d\n",hep4Index, hep4[hep4Index], Heptagon);
	createPath(p);
}
