#ifdef PROBLEM_DESCRIPTION

Pentagon numbers


Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

#endif

#include <stdio.h>
#include <math.h>

#define DEBUG_P44 0

long nPent(long n)  // if n is a pentagon number, nPent returns k, where Pk = n,
{					// if not a pentagon number, -1 is returned
	long rad = 24 * n + 1;
	long s = sqrt((double)rad) + 0.3;
	if (s * s != rad) { if (DEBUG_P44) printf("s: %ld  s^2: %ld is not equal to %ld\n", s, s*s, rad); 
		return -1; }
	if ( (s + 1) % 6 == 0) return (s+1)/6;
	if (DEBUG_P44) printf("s: %ld  s+1 not divisible by 6\n", s);
	return -1;
}

bool isPent(long n)
{
	if (nPent(n) >= 0) return true;
	return false;
}

long PentN(long n)
{
	return (3 * n - 1) * n / 2;
}


int main()
{
	for (long n = 1; n <= 100000; n++)
	{
		long pn = PentN(n);
		for (long k = 1; k < n; k++)
		{
			long pk = PentN(k);
			long add = nPent(pn + pk);
			long min = nPent(pn - pk);
			if (add > 0 && min > 0) {
				printf("P(%ld)  =  %ld  P(%ld)  =  %ld  \n", n, pn, k, pk);
				printf("     Add: %ld (%ld)    Minus %ld (%ld)\n",
						pn+pk, add, pn-pk, min);
			}
		}
	}
}
