
/*
Distinct powers
Problem 29

Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

    2^2=4, 2^3=8, 2^4=16, 2^5=32
    3^2=9, 3^3=27, 3^4=81, 3^5=243
    4^2=16, 4^3=64, 4^4=256, 4^5=1024
    5^2=25, 5^3=125, 5^4=625, 5^5=3125

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
*/

#include "vdouble.h"
#include "bigint.h"

void check(int n)
{
	double a, b;
	vdouble v(1e-7); // 1^-7 .. 1^-10 was the epsilon needed to make this work correctly - 
						// 0 did not work
	for (a = 2; a <= n; a+=1.0)
	{
		for (b = 2; b <= n; b+=1.0)
		{
			double x = b * log(a);
			v.add(x);
		}
	}
	printf("N = %d  Number of unique values using Log(n) list: %ld\n", n, v.size());
}

// return true if value exists in vector
//

vector<BigInt> gv;


inline
bool  exists(BigInt &v) 
{
	for (vector<BigInt>::iterator i = gv.begin(); i != gv.end(); i++)
	    if (*i == v) return true;
	return false;
}



#define P(s, a, b, v)  //printf("%s :: a = %s   b = %s   a^b = %s\n", s, a.c_str(), b.c_str(), v.c_str())

inline
bool	gvadd(BigInt &a, BigInt &b)
{
	BigInt v = a^b;
	if (gv.size() == 0){gv.push_back(v); P("Adding", a, b, v); return true;}
	//
	if (exists(v)) {  P("Exists", a, b, v); return false; }
	P("Adding", a, b, v);
	gv.push_back(v);
	return true;
}

void checkb(long n)
{
	gv.clear();
	BigInt a, b;
	for (a = 2; a <= n; a+=1.0)
	{
		for (b = 2; b <= n; b+=1.0)
		{
			gvadd(a, b);
		}
	}
	printf("N = %ld  Number of unique values using BigInt: %ld\n", n, gv.size());
}

int main()
{
	//checkb(5);
	//checkb(10);
	checkb(100);
	check(100);
	return 1;
	for (int n = 10; n <= 100; n++) check(n);
	//return 1;
	double a, b;
	vdouble v(0.0000000000001);
	int count = 0;
	for (a = 2; a <= 10.1; a+=1.0)
	{
		for (b = 2; b <= 10.1; b+=1.0)
		{
			double x = b * log(a);
			if (!v.add(x)) printf("[%d] a = %f    b = %f\n", ++count, a, b);
		}
	}
	vdouble g(0.0000000001);
	g.add( 2 * log(4) );
	g.add( 4 * log(2) );
	g.out();
	printf("2log4 = %f   4log2 = %f\n", 2 * log(4), 4 * log(2));
	printf("Number of unique values: %ld\n", v.size());
}
